# permissions for end users to edit ghostblogs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: ghostblog-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: cms-operator
    app.kubernetes.io/part-of: cms-operator
    app.kubernetes.io/managed-by: kustomize
  name: ghostblog-editor-role
rules:
- apiGroups:
  - cms.wellcom.rocks
  resources:
  - ghostblogs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cms.wellcom.rocks
  resources:
  - ghostblogs/status
  verbs:
  - get
