---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cms.wellcom.rocks
  resources:
  - ghostblogs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cms.wellcom.rocks
  resources:
  - ghostblogs/finalizers
  verbs:
  - update
- apiGroups:
  - cms.wellcom.rocks
  resources:
  - ghostblogs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cms.wellcom.rocks
  resources:
  - wordpresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cms.wellcom.rocks
  resources:
  - wordpresses/finalizers
  verbs:
  - update
- apiGroups:
  - cms.wellcom.rocks
  resources:
  - wordpresses/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
