apiVersion: cms.wellcom.rocks/v1alpha1
kind: GhostBlog
metadata:
  labels:
    app.kubernetes.io/name: ghostblog
    app.kubernetes.io/instance: ghostblog-sample
    app.kubernetes.io/part-of: cms-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: cms-operator
  name: ghostblog-sample
spec:
  size: 1
  containerPort: 2368
  image: ghost:5.79.0
  config:
    url: http://ghost.example.com
    database:
      client: sqlite3
      connection:
        filename: /var/lib/ghost/content/data/ghost.db
  persistent:
    enabled: true
    size: 5Gi
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    tls:
      enabled: false
      secretName: ghost-tls
    hosts:
      - ghost.example.com