apiVersion: cms.wellcom.rocks/v1alpha1
kind: Wordpress
metadata:
  labels:
    app.kubernetes.io/name: wordpress
    app.kubernetes.io/instance: wordpress-sample
    app.kubernetes.io/part-of: cms-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: cms-operator
  name: wordpress-sample
spec:
  # TODO(user): Add fields here
